apiVersion: v1
kind: Service
metadata:
  name: metallb-test
spec:
  selector:
    app: metallb-test
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-test
  labels:
    app: metallb-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metallb-test
  template:
    metadata:
      labels:
        app: metallb-test
    spec:
      containers:
        - name: metallb-test
          image: httpd
          ports:
            - containerPort: 80

