---

- name: Configure deplab servers
  hosts: deplab
  gather_facts: false
  tasks:

    - name: Wait for deplab servers to be available
      ansible.builtin.wait_for_connection:
        timeout: 180
        sleep: 10

    - name: Gather facts
      ansible.builtin.setup:

    - name: Update packages
      ansible.builtin.apt:
        name: '*'
        update_cache: true
      register: update_packages

    - name: Reboot if packages updated
      ansible.builtin.reboot: # noqa no-handler
      when: update_packages.changed

    - name: Create TFTP directory
      ansible.builtin.file:
        path: /pxeboot
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Install pxelinux and syslinux
      ansible.builtin.apt:
        pkg:
          - pxelinux
          - syslinux-common

    - name: Copy pxelinux files to TFTP directory
      ansible.builtin.copy:
        src: /usr/lib/PXELINUX/pxelinux.0
        dest: /pxeboot
        owner: root
        group: root
        mode: 0644
        remote_src: true

    - name: Copy syslinux files to TFTP directory
      ansible.posix.synchronize:
        src: /usr/lib/syslinux/modules/bios/
        dest: /pxeboot
        archive: true
      delegate_to: '{{ inventory_hostname }}'

    - name: Create pxelinux.cfg directory
      ansible.builtin.file:
        path: /pxeboot/pxelinux.cfg
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: Configure pxelinux
      ansible.builtin.copy:
        dest: /pxeboot/pxelinux.cfg/default
        owner: root
        group: root
        mode: 0644
        # yamllint disable rule:line-length
        content: |
          DEFAULT menu.c32
          PROMPT 0
          MENU TITLE PXE Menu
          TIMEOUT 0
          LABEL Ubuntu2204
            MENU LABEL Install Ubuntu Server 22.04.1 LTS
            KERNEL vmlinuz
            INITRD initrd
            APPEND url=http://192.168.248.11/ubuntu-22.04.1-live-server-amd64.iso autoinstall ds=nocloud-net;s=http://192.168.248.11/ cloud-config-url=/dev/null ip=dhcp fsck.mode=skip ---
        # yamllint enable rule:line-length

    - name: Install dnsmasq
      ansible.builtin.apt:
        name: dnsmasq

    - name: Configure dnsmasq
      ansible.builtin.copy:
        dest: /etc/dnsmasq.conf
        owner: root
        group: root
        mode: 0644
        content: |
          port=0
          interface=ens4
          bind-interfaces
          dhcp-range=ens4,192.168.248.200,192.168.248.249,255.255.255.0,5m
          dhcp-option=option:router,192.168.248.11
          dhcp-option=option:dns-server,8.8.8.8
          dhcp-option=option:dns-server,8.8.4.4
          enable-tftp
          tftp-root=/pxeboot
          dhcp-boot=pxelinux.0
      register: configure_dnsmasq

    - name: Restart dnsmaq if configuration changed
      ansible.builtin.service: # noqa no-handler
        name: dnsmasq
        state: restarted
      when: configure_dnsmasq.changed

    - name: Start and enable dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true

    - name: Install Apache
      ansible.builtin.apt:
        name: apache2

    - name: Start and enable Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Copy Ubuntu ISO to Apache directory
      ansible.builtin.copy:
        src: ubuntu-22.04.1-live-server-amd64.iso
        dest: /var/www/html/ubuntu-22.04.1-live-server-amd64.iso
        owner: root
        group: root
        mode: 0644

    - name: Install p7zip (required to extract files from ISO)
      ansible.builtin.apt:
        name: p7zip-full

    - name: Extract PXE boot files from Ubuntu ISO
      community.general.iso_extract:
        image: /var/www/html/ubuntu-22.04.1-live-server-amd64.iso
        dest: /pxeboot
        files:
          - casper/vmlinuz
          - casper/initrd

    - name: Create autoinstall user data file
      ansible.builtin.copy:
        dest: /var/www/html/user-data
        owner: root
        group: root
        mode: 0644
        content: |
          #cloud-config
          autoinstall:
            apt:
              disable_components: []
              geoip: true
              preserve_sources_list: false
              primary:
              - arches:
                - amd64
                - i386
                uri: http://us.archive.ubuntu.com/ubuntu
              - arches:
                - default
                uri: http://ports.ubuntu.com/ubuntu-ports
            drivers:
              install: false
            identity:
              hostname: deplabclient1
              password: $6$36cwdjJBC71W2L1G$FKwol67dwqPQwC2zeLsEZc3EWyUgU0zC7s4AncLM9cz20f4hbXK0sdE97IYbxhbVe5GH0LvIhVxZWcNt8kzE41
              realname: Jason A. Fager
              username: jafager
            kernel:
              package: linux-generic
            keyboard:
              layout: us
              toggle: null
              variant: ''
            locale: en_US.UTF-8
            network:
              ethernets:
                ens3:
                  addresses:
                  - 192.168.248.21
                  gateway4: 192.168.248.11
                  nameservers:
                    addresses:
                    - 8.8.8.8
                    - 8.8.4.4
              version: 2
            source:
              id: synthesized
              search_drivers: false
            ssh:
              allow-pw: true
              authorized-keys: []
              install-server: true
            storage:
              config:
              - ptable: gpt
                path: /dev/sda
                wipe: superblock-recursive
                preserve: false
                name: ''
                grub_device: true
                type: disk
                id: disk-sda
              - device: disk-sda
                size: 1048576
                flag: bios_grub
                number: 1
                preserve: false
                grub_device: false
                offset: 1048576
                type: partition
                id: partition-0
              - device: disk-sda
                size: 1073741824
                wipe: superblock
                number: 2
                preserve: false
                grub_device: false
                offset: 2097152
                type: partition
                id: partition-1
              - fstype: ext4
                volume: partition-1
                preserve: false
                type: format
                id: format-0
              - device: disk-sda
                size: -1
                wipe: superblock
                number: 3
                preserve: false
                grub_device: false
                offset: 1075838976
                type: partition
                id: partition-2
              - name: rootvg
                devices:
                - partition-2
                preserve: false
                type: lvm_volgroup
                id: lvm_volgroup-0
              - name: swap
                volgroup: lvm_volgroup-0
                size: 2147483648B
                wipe: superblock
                preserve: false
                type: lvm_partition
                id: lvm_partition-0
              - fstype: swap
                volume: lvm_partition-0
                preserve: false
                type: format
                id: format-1
              - path: ''
                device: format-1
                type: mount
                id: mount-1
              - name: root
                volgroup: lvm_volgroup-0
                size: 17179869184B
                wipe: superblock
                preserve: false
                type: lvm_partition
                id: lvm_partition-1
              - fstype: ext4
                volume: lvm_partition-1
                preserve: false
                type: format
                id: format-2
              - path: /
                device: format-2
                type: mount
                id: mount-2
              - path: /boot
                device: format-0
                type: mount
                id: mount-0
              swap:
                swap: 0
            updates: security
            timezone: America/New_York
            shutdown: poweroff
            version: 1
    - name: Install NFS server
      ansible.builtin.apt:
        name: nfs-kernel-server

    - name: Add NFS export
      ansible.builtin.lineinfile:
        dest: /etc/exports
        regex: '^\s*/pxeboot\b.*$'
        line: '/pxeboot 192.168.248.0/24(ro)'
      register: add_nfs_export

    - name: Start and enable NFS server
      ansible.builtin.service:
        name: nfs-server
        state: started
        enabled: true

    - name: Reload exports if export file changed
      ansible.builtin.command: # noqa no-handler
        cmd: exportfs -r
      when: add_nfs_export.changed

    - name: Configure UFW sysctl forwarding
      ansible.builtin.lineinfile:
        path: /etc/ufw/sysctl.conf
        regex: '^net.ipv4.ip_forward\s*=.*$'
        line: 'net.ipv4.ip_forward=1'

    - name: Reset and disable UFW
      community.general.ufw:
        state: reset

    - name: Configure UFW masquerading
      ansible.builtin.blockinfile:
        path: /etc/ufw/before.rules
        block: |
          *nat
          :POSTROUTING ACCEPT [0:0]
          -A POSTROUTING -s 192.168.248.0/24 -o ens3 -j MASQUERADE
          COMMIT

    - name: Default deny incoming traffic
      community.general.ufw:
        direction: incoming
        default: deny

    - name: Default allow forwarded traffic
      community.general.ufw:
        direction: routed
        default: allow

    - name: Allow all traffic on internal interface
      community.general.ufw:
        interface_in: ens4
        rule: allow

    - name: Allow SSH traffic on external interface
      community.general.ufw:
        interface_in: ens3
        port: 22
        proto: tcp
        rule: allow

    - name: Enable UFW
      community.general.ufw:
        state: enabled
