apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    app: centos
spec:
  containers:
    - name: centos
      image: centos:7
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
