---

- name: Configure kadmlablb servers
  hosts: kadmlablb
  gather_facts: false
  tasks:

    - name: Wait for kadmlablb servers to be available
      ansible.builtin.wait_for_connection:
        timeout: 180
        sleep: 10

    - name: Gather facts
      ansible.builtin.setup:

    - name: Update packages
      ansible.builtin.apt:
        name: '*'
        update_cache: true
      register: update_packages

    - name: Reboot if packages updated
      ansible.builtin.reboot: # noqa no-handler
      when: update_packages.changed

    - name: Install HAProxy prerequisites
      ansible.builtin.apt:
        pkg:
          - software-properties-common

    - name: Add HAProxy repository
      ansible.builtin.apt_repository:
        repo: ppa:vbernat/haproxy-2.6

    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy=2.6.*
        update_cache: true

    - name: Configure HAProxy for Kubernetes
      ansible.builtin.blockinfile:
        path: /etc/haproxy/haproxy.cfg
        backup: true
        block: |
          frontend controlplane.kadmlab.prism.local
            mode tcp
            bind *:6443
            default_backend controlplane

          backend controlplane
            balance roundrobin
            mode tcp
            server klabadmnode1 192.168.251.11:6443 check
            server klabadmnode2 192.168.251.12:6443 check
            server klabadmnode3 192.168.251.13:6443 check
      register: configure_haproxy

    - name: Restart haproxy if necessary
      ansible.builtin.service: # noqa no-handler
        name: haproxy
        state: restarted
      when: configure_haproxy.changed

    - name: Start and enable haproxy
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: true

    - name: Install keepalived
      ansible.builtin.apt:
        name: keepalived

    - name: Configure keepalived for Kubernetes
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        owner: root
        group: root
        mode: 0644
        content: |
          global_defs {
            enable_script_security
            script_user root
          }
          vrrp_script haproxy_controlplane {
            script "/usr/bin/pgrep haproxy"
            interval 2
          }
          vrrp_instance controlplane {
            interface ens4
            state {{ keepalived_state }}
            priority {{ keepalived_priority }}
            virtual_router_id 20
            unicast_src_ip {{ keepalived_source_ip }}
            unicast_peer {
              {{ keepalived_peer }}
            }
            authentication {
              auth_type PASS
              auth_pass mmq7rgzH
            }
            track_script {
              haproxy_controlplane
            }
            virtual_ipaddress {
              192.168.251.100/24 dev ens4 label ens4:1
            }
          }
      register: configure_keepalived

    - name: Restart keepalived if necessary
      ansible.builtin.service: # noqa no-handler
        name: keepalived
        state: restarted
      when: configure_keepalived.changed

    - name: Start and enable keepalived
      ansible.builtin.service:
        name: keepalived
        state: started
        enabled: true
